services:
  - type: web
    name: automl-studio
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python main.py
    startCommand: uvicorn streamlit_app.app:app --host 0.0.0.0 --port $PORT
